name: golangci-lint

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
  pull_request:

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4.1.3

      - uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4.1.0
        with:
          go-version: '1.20'
          check-latest: true

      - name: golangci-lint
        uses: golangci/golangci-lint-action@3a919529898de77ec3da873e3063ca4b10e7f5cc # v3.7.0
        with:
          version: v1.55
          args: --timeout=15m
